/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.bdozer.core.nlp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AnswerQuestionResponse
 */
class AnswerQuestionResponseTest {
    private final AnswerQuestionResponse model = new AnswerQuestionResponse();

    /**
     * Model tests for AnswerQuestionResponse
     */
    @Test
    void testAnswerQuestionResponse() {
        // TODO: test AnswerQuestionResponse
    }

    /**
     * Test the property 'question'
     */
    @Test
    void questionTest() {
        // TODO: test question
    }

    /**
     * Test the property 'bestAnswer'
     */
    @Test
    void bestAnswerTest() {
        // TODO: test bestAnswer
    }

}
