/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.bdozer.core.nlp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ScoredSentence
 */
class ScoredSentenceTest {
    private final ScoredSentence model = new ScoredSentence();

    /**
     * Model tests for ScoredSentence
     */
    @Test
    void testScoredSentence() {
        // TODO: test ScoredSentence
    }

    /**
     * Test the property 'sentence'
     */
    @Test
    void sentenceTest() {
        // TODO: test sentence
    }

    /**
     * Test the property 'score'
     */
    @Test
    void scoreTest() {
        // TODO: test score
    }

}
