create table mt
(
    m_ticker            varchar,
    ticker              varchar,
    comp_name           varchar,
    comp_name_2         varchar,
    exchange            varchar,
    currency_code       varchar,
    ticker_type         char,
    active_ticker_flag  varchar,
    comp_url            varchar,
    sic_4_code          int,
    sic_4_desc          varchar,
    zacks_x_ind_code    int,
    zacks_x_ind_desc    varchar,
    zacks_x_sector_code int,
    zacks_x_sector_desc varchar,
    zacks_m_ind_code    int,
    zacks_m_ind_desc    varchar,
    per_end_month_nbr   int,
    mr_split_date       date,
    mr_split_factor     numeric,
    comp_cik            varchar,
    country_code        varchar,
    country_name        varchar,
    comp_type           int,
    optionable_flag     varchar,
    sp500_member_flag   varchar,
    asset_type          char(3),
    primary key (m_ticker)
);
