create table se
(
    m_ticker                  varchar,
    ticker                    varchar,
    comp_name                 varchar,
    comp_name_2               varchar,
    exchange                  varchar,
    currency_code             char(3),
    per_end_date              date,
    per_type                  char,
    per_code                  varchar,
    per_fisc_year             int,
    per_fisc_qtr              int,
    per_cal_year              int,
    per_cal_qtr               int,
    ann_rpt_flag              int,
    qtr_rpt_flag              int,
    last_rev_date             date,
    sales_mean_est            numeric,
    sales_median_est          numeric,
    sales_cnt_est             int,
    sales_high_est            numeric,
    sales_low_est             numeric,
    sales_std_dev_est         numeric,
    sales_pct_chg_est_1w      numeric,
    sales_cnt_est_rev_up_1w   int,
    sales_cnt_est_rev_down_1w int,
    sales_pct_chg_est_1m      numeric,
    sales_cnt_est_rev_up_1m   int,
    sales_cnt_est_rev_down_1m int,
    sales_pct_chg_est_3m      numeric,
    sales_cnt_est_rev_up_3m   int,
    sales_cnt_est_rev_down_3m int,
    primary key (m_ticker, per_end_date, per_type)
)