package co.bdozer.libraries.zacks.models

import java.time.LocalDate

data class FR(
    val m_ticker: String,
    val ticker: String?,
    val comp_name: String?,
    val comp_name_2: String?,
    val exchange: String?,
    val currency_code: String?,
    val per_end_date: LocalDate,
    val per_type: String,
    val per_code: String?,
    val per_fisc_year: Int,
    val per_fisc_qtr: Int,
    val per_cal_year: Int,
    val per_cal_qtr: Int,
    val form_7_type: Int,
    val curr_ratio: Double?,
    val non_perform_asset_tot_loan: Double?,
    val loan_loss_reserve: Double?,
    val lterm_debt_cap: Double?,
    val tot_debt_tot_equity: Double?,
    val gross_margin: Double?,
    val oper_profit_margin: Double?,
    val ebit_margin: Double?,
    val ebitda_margin: Double?,
    val pretax_profit_margin: Double?,
    val profit_margin: Double?,
    val free_cash_flow: Double?,
    val loss_ratio: Double?,
    val exp_ratio: Double?,
    val comb_ratio: Double?,
    val asset_turn: Double?,
    val invty_turn: Double?,
    val rcv_turn: Double?,
    val day_sale_rcv: Double?,
    val ret_equity: Double?,
    val ret_tang_equity: Double?,
    val ret_asset: Double?,
    val ret_invst: Double?,
    val free_cash_flow_per_share: Double?,
    val book_val_per_share: Double?,
    val oper_cash_flow_per_share: Double?,
)
