package com.bdozer.edgar.factbase


object USGaapConstants {
    const val IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest =
        "IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest"
    const val IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments =
        "IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments"
    const val AccountsPayableCurrent = "AccountsPayableCurrent"
    const val AccountsReceivableNetCurrent = "AccountsReceivableNetCurrent"
    const val AccruedLiabilitiesandOtherLiabilitiesCurrent = "AccruedLiabilitiesandOtherLiabilitiesCurrent"
    const val AccumulatedOtherComprehensiveIncomeLossNetOfTax = "AccumulatedOtherComprehensiveIncomeLossNetOfTax"
    const val AdditionalPaidInCapital = "AdditionalPaidInCapital"
    const val AssetImpairmentCharges = "AssetImpairmentCharges"
    const val AvailableForSaleSecuritiesDebtSecuritiesCurrent = "AvailableForSaleSecuritiesDebtSecuritiesCurrent"
    const val CapitalizedContractCostAmortization = "CapitalizedContractCostAmortization"
    const val CashAndCashEquivalentsAtCarryingValue = "CashAndCashEquivalentsAtCarryingValue"
    const val CommitmentsAndContingencies = "CommitmentsAndContingencies"
    const val CommonStockValue = "CommonStockValue"
    const val ContractWithCustomerLiabilityCurrent = "ContractWithCustomerLiabilityCurrent"
    const val CostOfGoodsAndServicesSold = "CostOfGoodsAndServicesSold"
    const val DeprecationDepletionAndAmortizationExcludingAmortizationOfDeferredSalesCommissions =
        "DeprecationDepletionAndAmortizationExcludingAmortizationOfDeferredSalesCommissions"
    const val EffectOfExchangeRateOnCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents =
        "EffectOfExchangeRateOnCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents"
    const val EmployeeRelatedLiabilitiesCurrent = "EmployeeRelatedLiabilitiesCurrent"
    const val EquitySecuritiesFvNiGainLoss = "EquitySecuritiesFvNiGainLoss"
    const val FinanceLeaseLiabilityCurrent = "FinanceLeaseLiabilityCurrent"
    const val FinanceLeaseLiabilityNoncurrent = "FinanceLeaseLiabilityNoncurrent"
    const val FinanceLeasePrincipalPayments = "FinanceLeasePrincipalPayments"
    const val GeneralAndAdministrativeExpense = "GeneralAndAdministrativeExpense"
    const val Goodwill = "Goodwill"
    const val IncomeTaxExpenseBenefit = "IncomeTaxExpenseBenefit"
    const val IncomeLossFromEquityMethodInvestmentsAndOtherThanTemporaryImpairment =
        "IncomeLossFromEquityMethodInvestmentsAndOtherThanTemporaryImpairment"
    const val SpecialItems = "SpecialItems"
    const val RestructuringAndOtherExpenseIncomeMainline = "RestructuringAndOtherExpenseIncomeMainline"
    const val IncreaseDecreaseInAccountsAndOtherReceivables = "IncreaseDecreaseInAccountsAndOtherReceivables"
    const val IncreaseDecreaseInAccountsPayable = "IncreaseDecreaseInAccountsPayable"
    const val IncreaseDecreaseInAccruedLiabilitiesAndOtherLiabilities =
        "IncreaseDecreaseInAccruedLiabilitiesAndOtherLiabilities"
    const val IncreaseDecreaseInContractWithCustomerLiability = "IncreaseDecreaseInContractWithCustomerLiability"
    const val IncreaseDecreaseInEmployeeRelatedLiabilities = "IncreaseDecreaseInEmployeeRelatedLiabilities"
    const val IncreaseDecreaseInOtherNoncurrentLiabilities = "IncreaseDecreaseInOtherNoncurrentLiabilities"
    const val IncreaseDecreaseInOtherOperatingAssets = "IncreaseDecreaseInOtherOperatingAssets"
    const val IncreaseDecreaseInPrepaidDeferredExpenseAndOtherAssets =
        "IncreaseDecreaseInPrepaidDeferredExpenseAndOtherAssets"
    const val IncreaseDecreaseTenantImprovementAllowanceReimbursement =
        "IncreaseDecreaseTenantImprovementAllowanceReimbursement"
    const val IntangibleAssetsNetExcludingGoodwill = "IntangibleAssetsNetExcludingGoodwill"
    const val InterestExpense = "InterestExpense"
    const val InterestIncomeExpenseNonoperatingNet = "InterestIncomeExpenseNonoperatingNet"
    const val OperatingLeaseLiabilityCurrent = "OperatingLeaseLiabilityCurrent"
    const val OperatingLeaseLiabilityNoncurrent = "OperatingLeaseLiabilityNoncurrent"
    const val OperatingLeaseRightOfUseAsset = "OperatingLeaseRightOfUseAsset"
    const val OtherAssetsNoncurrent = "OtherAssetsNoncurrent"
    const val OtherLiabilitiesNoncurrent = "OtherLiabilitiesNoncurrent"
    const val OtherNoncashIncomeExpense = "OtherNoncashIncomeExpense"
    const val OtherNonoperatingIncomeExpense = "OtherNonoperatingIncomeExpense"
    const val PaymentsForProceedsFromOtherInvestingActivities = "PaymentsForProceedsFromOtherInvestingActivities"
    const val PaymentsForRepurchaseOfCommonStock = "PaymentsForRepurchaseOfCommonStock"
    const val PaymentsOfStockIssuanceCosts = "PaymentsOfStockIssuanceCosts"
    const val PaymentsRelatedToTaxWithholdingForShareBasedCompensation =
        "PaymentsRelatedToTaxWithholdingForShareBasedCompensation"
    const val PaymentsToAcquireAvailableForSaleSecuritiesDebt = "PaymentsToAcquireAvailableForSaleSecuritiesDebt"
    const val PaymentsToAcquireBusinessesNetOfCashAcquired = "PaymentsToAcquireBusinessesNetOfCashAcquired"
    const val PaymentsToAcquireIntangibleAssets = "PaymentsToAcquireIntangibleAssets"
    const val PaymentsToAcquirePropertyPlantAndEquipment = "PaymentsToAcquirePropertyPlantAndEquipment"
    const val PreferredStockValue = "PreferredStockValue"
    const val PrepaidExpenseAndOtherAssetsCurrent = "PrepaidExpenseAndOtherAssetsCurrent"
    const val ProceedsFromIssuanceInitialPublicOffering = "ProceedsFromIssuanceInitialPublicOffering"
    const val ProceedsFromIssuanceOfCommonStock = "ProceedsFromIssuanceOfCommonStock"
    const val ProceedsFromMaturitiesPrepaymentsAndCallsOfShorttermInvestments =
        "ProceedsFromMaturitiesPrepaymentsAndCallsOfShorttermInvestments"
    const val ProceedsFromPaymentsForOtherFinancingActivities = "ProceedsFromPaymentsForOtherFinancingActivities"
    const val ProceedsFromSaleOfShortTermInvestments = "ProceedsFromSaleOfShortTermInvestments"
    const val PropertyPlantAndEquipmentNet = "PropertyPlantAndEquipmentNet"
    const val ResearchAndDevelopmentExpense = "ResearchAndDevelopmentExpense"
    const val RetainedEarningsAccumulatedDeficit = "RetainedEarningsAccumulatedDeficit"
    const val RevenueFromContractWithCustomerExcludingAssessedTax =
        "RevenueFromContractWithCustomerExcludingAssessedTax"
    const val RevenueFromContractWithCustomerIncludingAssessedTax =
        "RevenueFromContractWithCustomerIncludingAssessedTax"
    const val SellingAndMarketingExpense = "SellingAndMarketingExpense"
    const val ShareBasedCompensation = "ShareBasedCompensation"

    const val EarningsPerShareDiluted = "EarningsPerShareDiluted"
    const val EarningsPerShareBasicAndDiluted = "EarningsPerShareBasicAndDiluted"
    const val EarningsPerShareBasic = "EarningsPerShareBasic"
    const val WeightedAverageNumberOfDilutedSharesOutstanding = "WeightedAverageNumberOfDilutedSharesOutstanding"
    const val WeightedAverageNumberOfShareOutstandingBasicAndDiluted =
        "WeightedAverageNumberOfShareOutstandingBasicAndDiluted"
    const val WeightedAverageNumberOfSharesOutstandingBasic = "WeightedAverageNumberOfSharesOutstandingBasic"
    const val EntityCommonStockSharesOutstanding = "EntityCommonStockSharesOutstanding"
    const val NetIncomeLoss = "NetIncomeLoss"
    const val CostsAndExpenses = "CostsAndExpenses"
    const val OperatingCostsAndExpenses = "OperatingCostsAndExpenses"
    const val OperatingExpenses = "OperatingExpenses"
    const val OperatingIncomeLoss = "OperatingIncomeLoss"
}