/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.bdozer.core.nlp.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AnswerQuestionResponse
 */
@JsonPropertyOrder({
  AnswerQuestionResponse.JSON_PROPERTY_QUESTION,
  AnswerQuestionResponse.JSON_PROPERTY_BEST_ANSWER
})
@JsonTypeName("AnswerQuestionResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-22T19:20:31.952-04:00[America/New_York]")
public class AnswerQuestionResponse {
  public static final String JSON_PROPERTY_QUESTION = "question";
  private String question;

  public static final String JSON_PROPERTY_BEST_ANSWER = "best_answer";
  private String bestAnswer;

  public AnswerQuestionResponse() { 
  }

  public AnswerQuestionResponse question(String question) {
    
    this.question = question;
    return this;
  }

   /**
   * Get question
   * @return question
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_QUESTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQuestion() {
    return question;
  }


  @JsonProperty(JSON_PROPERTY_QUESTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuestion(String question) {
    this.question = question;
  }


  public AnswerQuestionResponse bestAnswer(String bestAnswer) {
    
    this.bestAnswer = bestAnswer;
    return this;
  }

   /**
   * Get bestAnswer
   * @return bestAnswer
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BEST_ANSWER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBestAnswer() {
    return bestAnswer;
  }


  @JsonProperty(JSON_PROPERTY_BEST_ANSWER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBestAnswer(String bestAnswer) {
    this.bestAnswer = bestAnswer;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnswerQuestionResponse answerQuestionResponse = (AnswerQuestionResponse) o;
    return Objects.equals(this.question, answerQuestionResponse.question) &&
        Objects.equals(this.bestAnswer, answerQuestionResponse.bestAnswer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(question, bestAnswer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnswerQuestionResponse {\n");
    sb.append("    question: ").append(toIndentedString(question)).append("\n");
    sb.append("    bestAnswer: ").append(toIndentedString(bestAnswer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

